### ISSUE TITLE
How can you use string as "yourdata"

### ISSUE THREAD

**Issue by samisabik** [ericbenwa/POST-Arduino-Data-Wireless#2]
Hello,

Thank you very much for the piece of code, works like a charm !
But ... for my application I want to send from the Arduino to MySQL not value but string ! And I've tried to twist the code in every way possible i can't manage to send strings ! maybe you could give me some help ;)

**Comment by samisabik** [comment]
Actually I just managed, it was pretty simple :)

String yourdata = "yourdata='yourtext'";

**Comment by ericbenwa** [comment]
Neat!

So you just swapped line 16 of arduino_post.ino from _String yourdata;_ to yours _String yourdata = "yourdata='yourtext'";_

?

**Comment by samisabik** [comment]
yes!

**Comment by ericbenwa** [comment]
Sweet.
Thanks for figuring that out!
