### ISSUE TITLE
client.print

### ISSUE THREAD

**Issue by nabeelismaeel** [ericbenwa/POST-Arduino-Data-Wireless#3]
Hi! I am trying to understand the project and one thing is bothering me. You have called the print function like this:
client.println("String");
But there is no print(ln) function in the wificlient class. Also there is a line in wificlient.h which says:
using Print::writre
So can you help me figure out how this works when you call the print function using an object of wificlient class?
PS: I know I am asking a question 6 years after you made the post xD

**Comment by ericbenwa** [comment]
Are you able to share your code?
Which file(s) and line(s) are you looking at?
What happens when you run the file?
Maybe Arduino has updated their files since this repo was created... ? My memory is a bit foggy at this point.

**Comment by nabeelismaeel** [comment]
I have not run the file yet neither have I uploaded the code to arduino. Actually my application is a bit similar and for this reason i was looking into your project. My  question is regarding the following lines:


    // EDIT: The POST 'URL' to the location of your insert_mysql.php on your web-host
    client.println("POST /insert_mysql.php HTTP/1.1");

    // EDIT: 'Host' to match your domain
    client.println("Host: www.yourdomain.com");
    client.println("User-Agent: Arduino/1.0");
    client.println("Connection: close");
    client.println("Content-Type: application/x-www-form-urlencoded;");
    client.print("Content-Length: ");
    client.println(yourdata.length());
    client.println();
    client.println(yourdata); 

What happens when print(ln) is called in these lines? There is no print(ln) function inn the wificlient class and this "client" here is an object of the wificlient class. Is the wificlient class inheriting some class which has the print(ln) method? Does the using print statement mean inheritance? If so, where can I find this print class or these print(ln) methods.

Thanks for the response, I was not hoping for it because of the 6 year gap xD

**Comment by ericbenwa** [comment]
I believe what's happening in that section of the code is that it's structuring the POST request to write the data from the arduino to an online service.

Isn't `println()` a standard function?
https://www.arduino.cc/reference/en/language/functions/communication/serial/println/
`Prints data to the serial port as human-readable ASCII text followed by a carriage return character (ASCII 13, or '\r') and a newline character (ASCII 10, or '\n'). This command takes the same forms as Serial.print().`

**Comment by nabeelismaeel** [comment]
Alright thanks!!
